-- ============================================================
-- GESTIONALE ROSARIO FURNARI — Custom Schema
-- Migration: 20260225180000_gestionale_schema.sql
-- Description: Creates all tables for the custom gestionale
-- ============================================================

-- CLIENTI
CREATE TABLE IF NOT EXISTS public.clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  client_type TEXT NOT NULL CHECK (client_type IN (
    'produzione_tv', 'azienda_locale', 'privato_wedding', 'privato_evento', 'web'
  )),
  phone TEXT,
  email TEXT,
  address TEXT,
  tax_id TEXT,
  source TEXT CHECK (source IN (
    'instagram', 'facebook', 'passaparola', 'google', 'altro'
  )),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- PROGETTI / PROGRAMMI
CREATE TABLE IF NOT EXISTS public.projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN (
    'produzione_tv', 'spot', 'wedding', 'evento_privato', 'sviluppo_web'
  )),
  tv_show TEXT CHECK (tv_show IN (
    'bella_tra_i_fornelli', 'gustare_sicilia', 'vale_il_viaggio', 'altro'
  )),
  status TEXT DEFAULT 'in_corso' CHECK (status IN (
    'in_corso', 'completato', 'in_pausa', 'cancellato'
  )),
  start_date DATE,
  end_date DATE,
  budget DECIMAL(10,2),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- REGISTRO LAVORI (Servizi svolti)
CREATE TABLE IF NOT EXISTS public.services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  service_date DATE NOT NULL,
  service_type TEXT NOT NULL CHECK (service_type IN (
    'riprese', 'montaggio', 'riprese_montaggio', 'fotografia', 'sviluppo_web', 'altro'
  )),
  fee_shooting DECIMAL(10,2) DEFAULT 0,
  fee_editing DECIMAL(10,2) DEFAULT 0,
  fee_other DECIMAL(10,2) DEFAULT 0,
  km_distance INTEGER DEFAULT 0,
  km_rate DECIMAL(4,2) DEFAULT 0.19,
  location TEXT,
  invoice_ref TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- PREVENTIVI / PIPELINE
CREATE TABLE IF NOT EXISTS public.quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
  service_type TEXT NOT NULL,
  event_date DATE,
  description TEXT,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'primo_contatto' CHECK (status IN (
    'primo_contatto', 'preventivo_inviato', 'in_trattativa',
    'accettato', 'acconto_ricevuto', 'in_lavorazione',
    'completato', 'saldato', 'rifiutato', 'perso'
  )),
  sent_date DATE,
  response_date DATE,
  rejection_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- PAGAMENTI
CREATE TABLE IF NOT EXISTS public.payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES public.clients(id),
  project_id UUID REFERENCES public.projects(id),
  quote_id UUID REFERENCES public.quotes(id),
  payment_date DATE,
  payment_type TEXT CHECK (payment_type IN (
    'acconto', 'saldo', 'parziale', 'rimborso_spese'
  )),
  amount DECIMAL(10,2) NOT NULL,
  method TEXT CHECK (method IN (
    'bonifico', 'contanti', 'paypal', 'altro'
  )),
  invoice_ref TEXT,
  status TEXT DEFAULT 'in_attesa' CHECK (status IN (
    'ricevuto', 'in_attesa', 'scaduto'
  )),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- SPESE
CREATE TABLE IF NOT EXISTS public.expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES public.projects(id),
  client_id UUID REFERENCES public.clients(id),
  expense_date DATE NOT NULL,
  expense_type TEXT CHECK (expense_type IN (
    'spostamento_km', 'acquisto_materiale', 'noleggio', 'altro'
  )),
  km_distance INTEGER,
  km_rate DECIMAL(4,2) DEFAULT 0.19,
  amount DECIMAL(10,2),
  markup_percent DECIMAL(5,2) DEFAULT 0,
  description TEXT,
  invoice_ref TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- IMPOSTAZIONI
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- KEEP ALIVE (per evitare sospensione free tier)
CREATE TABLE IF NOT EXISTS public.keep_alive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT DEFAULT '',
  pinged_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- VALORI INIZIALI
-- ============================================================

INSERT INTO public.settings (key, value) VALUES
  ('default_km_rate', '0.19'),
  ('default_fee_shooting', '187'),
  ('default_fee_editing_standard', '249'),
  ('default_fee_editing_spot', '250'),
  ('default_fee_editing_short', '125'),
  ('currency', 'EUR');

INSERT INTO public.keep_alive (name) VALUES ('heartbeat');

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- Policy: solo utente autenticato può fare tutto
CREATE POLICY "Authenticated full access" ON public.clients
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.projects
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.services
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.quotes
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.payments
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.expenses
  FOR ALL USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated full access" ON public.settings
  FOR ALL USING (auth.uid() IS NOT NULL);

-- Keep alive: lettura pubblica (per il ping da GitHub Actions)
CREATE POLICY "Public read keep_alive" ON public.keep_alive
  FOR SELECT USING (true);

-- ============================================================
-- VIEWS
-- ============================================================

-- Riepilogo finanziario per progetto
CREATE OR REPLACE VIEW public.project_financials AS
SELECT
  p.id AS project_id,
  p.name AS project_name,
  c.name AS client_name,
  p.category,
  COUNT(s.id) AS total_services,
  COALESCE(SUM(s.fee_shooting + s.fee_editing + s.fee_other), 0) AS total_fees,
  COALESCE(SUM(s.km_distance), 0) AS total_km,
  COALESCE(SUM(s.km_distance * s.km_rate), 0) AS total_km_cost,
  COALESCE(SUM(pay.amount) FILTER (WHERE pay.status = 'ricevuto'), 0) AS total_paid,
  COALESCE(SUM(s.fee_shooting + s.fee_editing + s.fee_other), 0) -
    COALESCE(SUM(pay.amount) FILTER (WHERE pay.status = 'ricevuto'), 0) AS balance_due
FROM public.projects p
JOIN public.clients c ON p.client_id = c.id
LEFT JOIN public.services s ON s.project_id = p.id
LEFT JOIN public.payments pay ON pay.project_id = p.id
GROUP BY p.id, p.name, c.name, p.category;

-- Riepilogo mensile
CREATE OR REPLACE VIEW public.monthly_revenue AS
SELECT
  DATE_TRUNC('month', s.service_date) AS month,
  p.category,
  SUM(s.fee_shooting + s.fee_editing + s.fee_other) AS revenue,
  SUM(s.km_distance) AS total_km,
  SUM(s.km_distance * s.km_rate) AS km_cost
FROM public.services s
JOIN public.projects p ON s.project_id = p.id
GROUP BY DATE_TRUNC('month', s.service_date), p.category
ORDER BY month DESC;
